name: 'Github Release Generator'
description: 'Generates a release based on commit messages and semantic versioning.'

branding:
  icon: 'package'
  color: 'blue'
  
inputs:
  github_token:
    description: 'GitHub token used for authentication'
    required: true
  add_description:
    description: 'Additional custom description for the release'
    required: false
    default: ''
  increment_type:
    description: 'Type of version increment: major, minor, or patch'
    required: false
    default: 'patch'
  github_username:
    description: 'GitHub username'
    required: true
  repo_name:
    description: 'Repository name'
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.add_description }}
    - ${{ inputs.increment_type }}
    - ${{ inputs.github_username }}
    - ${{ inputs.repo_name }}
